# This script builds a QA prompt by injecting the README prompt section.

from __future__ import annotations

from pathlib import Path
import re
import shutil
import subprocess
import sys


DATA_COLLECTION_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = DATA_COLLECTION_ROOT.parent
EXPERIMENTS_ROOT = REPO_ROOT / "experiments"

PROMPT_TEMPLATE = """Role:

You are a Senior Frontend QA Engineer and Lead UI/UX Designer. Your task is to evaluate a video recording of a web application generated by an AI. You must be critical, precise, and objective.

Input Data:

The Goal: The original prompt used to generate the app: "[PROMPT used for the experiment]"

The Evidence: The attached video file showing the app in action.

Evaluation Criteria:

Score the application in the following three categories on a strict scale of 1-10 (integers only).

1. Prompt Adherence Score (PA)

Definition: Measures how completely the output implements the specified behavior and constraints found in "The Goal."

Scoring Guide:

10: Every requested feature (e.g., specific buttons, specific colors, specific mechanics) is present and accurate.

5: Main features are present, but specific constraints (like color or layout requests) were ignored.

1: The resulting app ignores the prompt entirely.

2. Functional Correctness Score (FC)

Definition: Evaluates the stability, physics, and logic of the application based on visual evidence.

Scoring Guide:

10: Physics mimic reality (if applicable), controls are responsive, logic flows correctly, and there are no visible glitches or "broken" states.

5: The app functions but feels "janky" or has minor logic errors (e.g., collision detection is loose).

1: The app crashes, freezes, or the core functionality is broken.

3. UI Quality Score (UI)

Definition: Assesses visual design, layout, readability, color hierarchy, and clarity of controls.

Scoring Guide:

10: Professional, modern, accessible design. Good use of whitespace, consistent color palette, and clear typography.

5: "Engineer Art." It works, but uses raw default HTML styles, clashing colors, or poor spacing.

1: Unusable layout, overlapping text, or painful color contrast.

Output Format:

Please provide your evaluation in the following structure:

Analysis



Final Scorecard

MetricScore (1-10)ReasoningPrompt Adherence (PA)[X][One sentence justification]

Functional Correctness (FC)[X][One sentence justification]

UI Quality (UI)[X][One sentence justification]

"""


def newest_timestamp(path: Path) -> float:
    stat = path.stat()
    return getattr(stat, "st_birthtime", stat.st_mtime)


def find_newest_directory(root: Path) -> Path:
    directories = [
        entry
        for entry in root.iterdir()
        if entry.is_dir()
        and not entry.name.startswith(".")
    ]
    if not directories:
        raise FileNotFoundError("No directories found in the target folder.")
    return max(directories, key=newest_timestamp)


def confirm_prompt(message: str) -> bool:
    while True:
        try:
            choice = input(message).strip().lower()
        except (EOFError, KeyboardInterrupt):
            raise
        if choice in {"y", "n"}:
            return choice == "y"
        print("Please enter 'y' or 'n'.")


def find_readme_file(folder: Path) -> Path:
    readmes = [
        path
        for path in folder.iterdir()
        if path.is_file() and path.name.lower().startswith("readme")
    ]
    if not readmes:
        raise FileNotFoundError("No README file found in the target folder.")
    return sorted(readmes, key=lambda path: path.name.lower())[0]


def extract_prompt_section(text: str) -> str:
    lines = text.splitlines()
    start_index = None
    for idx, line in enumerate(lines):
        if re.match(r"^##\s+.*original prompt", line, re.IGNORECASE):
            start_index = idx + 1
            break

    if start_index is None:
        raise ValueError("Prompt section not found in README.")

    collected: list[str] = []
    for line in lines[start_index:]:
        stripped = line.strip()
        if re.match(r"^##\s+", line) or re.match(r"^#\s+", line) or stripped.startswith("---"):
            break
        collected.append(line)

    while collected and not collected[0].strip():
        collected.pop(0)
    while collected and not collected[-1].strip():
        collected.pop()

    return "\n".join(collected).strip()


def build_final_prompt(prompt_text: str) -> str:
    return PROMPT_TEMPLATE.replace("[PROMPT used for the experiment]", prompt_text)


def copy_to_clipboard(text: str) -> bool:
    if sys.platform == "darwin":
        try:
            subprocess.run(["pbcopy"], input=text, text=True, check=True)
            return True
        except Exception:
            pass

    for command in ("wl-copy", "xclip"):
        if shutil.which(command):
            try:
                if command == "xclip":
                    subprocess.run(
                        ["xclip", "-selection", "clipboard"],
                        input=text,
                        text=True,
                        check=True,
                    )
                else:
                    subprocess.run([command], input=text, text=True, check=True)
                return True
            except Exception:
                pass

    try:
        import tkinter as tk
    except Exception:
        return False

    try:
        root = tk.Tk()
        root.withdraw()
        root.clipboard_clear()
        root.clipboard_append(text)
        root.update()
        root.destroy()
        return True
    except Exception:
        return False


def main() -> int:
    root = EXPERIMENTS_ROOT
    try:
        newest_dir = find_newest_directory(root)
    except FileNotFoundError as exc:
        print(str(exc))
        return 1

    print(f"Latest folder found: '{newest_dir.name}'")
    try:
        if not confirm_prompt("this is the last folder created is this correct? y/n: "):
            print("Canceled.")
            return 1
    except (EOFError, KeyboardInterrupt):
        print("\nCanceled.")
        return 1

    try:
        readme_path = find_readme_file(newest_dir)
    except FileNotFoundError as exc:
        print(str(exc))
        return 1

    readme_text = readme_path.read_text(encoding="utf-8")
    try:
        prompt_text = extract_prompt_section(readme_text)
    except ValueError as exc:
        print(str(exc))
        return 1

    final_prompt = build_final_prompt(prompt_text)
    copied = copy_to_clipboard(final_prompt)
    try:
        display_path = readme_path.relative_to(root)
    except ValueError:
        display_path = readme_path

    print("=======")
    print(f"current prompt in {display_path} is ")
    print(prompt_text)
    print("=======")
    print()
    print("Prompt Template + current README prompt:")
    print(final_prompt)
    print()
    print("=======")
    if copied:
        print("\033[1m\033[32mPROMPT COPIED TO CLIPBOARD\033[0m")
    else:
        print("\033[1m\033[31mCLIPBOARD COPY FAILED\033[0m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
